import { Question } from '../../types';

export const SEED_QUIZ_TITLE = 'General Knowledge Challenge';
export const SEED_QUIZ_DESCRIPTION = 'Test your wits across Geography, Science, World History, Computing & Culture in a rapid-fire arena!';
export const SEED_QUIZ_CATEGORY = 'General Knowledge';

export const SEED_QUESTIONS: Omit<Question, 'id'>[] = [
  {
    questionType: 'MULTIPLE_CHOICE',
    questionText: 'Which ocean trench is the deepest known location on Earth?',
    explanation: 'The Mariana Trench in the western Pacific Ocean reaches depths of approximately 11,000 meters (Challenger Deep).',
    timeLimitSeconds: 20,
    points: 1000,
    sortOrder: 1,
    options: [
      { id: 'opt_1_a', text: 'Java Trench', sortOrder: 0 },
      { id: 'opt_1_b', text: 'Mariana Trench', sortOrder: 1 },
      { id: 'opt_1_c', text: 'Puerto Rico Trench', sortOrder: 2 },
      { id: 'opt_1_d', text: 'Tonga Trench', sortOrder: 3 },
    ],
    correctOptionId: 'opt_1_b',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    questionType: 'MULTIPLE_CHOICE',
    questionText: 'What element makes up approximately 78% of the Earth\'s atmosphere?',
    explanation: 'Nitrogen gas (N2) forms about 78.08% of Earth\'s dry atmosphere, followed by Oxygen at roughly 21%.',
    timeLimitSeconds: 20,
    points: 1000,
    sortOrder: 2,
    options: [
      { id: 'opt_2_a', text: 'Oxygen', sortOrder: 0 },
      { id: 'opt_2_b', text: 'Carbon Dioxide', sortOrder: 1 },
      { id: 'opt_2_c', text: 'Nitrogen', sortOrder: 2 },
      { id: 'opt_2_d', text: 'Argon', sortOrder: 3 },
    ],
    correctOptionId: 'opt_2_c',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    questionType: 'MULTIPLE_CHOICE',
    questionText: 'Who is widely credited with writing the first computer algorithm, intended for Babbage\'s Analytical Engine?',
    explanation: 'Ada Lovelace published the first algorithm designed to be carried out by a machine in 1843.',
    timeLimitSeconds: 20,
    points: 1000,
    sortOrder: 3,
    options: [
      { id: 'opt_3_a', text: 'Ada Lovelace', sortOrder: 0 },
      { id: 'opt_3_b', text: 'Alan Turing', sortOrder: 1 },
      { id: 'opt_3_c', text: 'Grace Hopper', sortOrder: 2 },
      { id: 'opt_3_d', text: 'Charles Babbage', sortOrder: 3 },
    ],
    correctOptionId: 'opt_3_a',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    questionType: 'MULTIPLE_CHOICE',
    questionText: 'Which ancient Mediterranean city was famous for the Library of Alexandria and Pharos Lighthouse?',
    explanation: 'Alexandria in Egypt was founded by Alexander the Great and was a premier hub of Hellenistic scholarship.',
    timeLimitSeconds: 20,
    points: 1000,
    sortOrder: 4,
    options: [
      { id: 'opt_4_a', text: 'Athens', sortOrder: 0 },
      { id: 'opt_4_b', text: 'Alexandria', sortOrder: 1 },
      { id: 'opt_4_c', text: 'Carthage', sortOrder: 2 },
      { id: 'opt_4_d', text: 'Constantinople', sortOrder: 3 },
    ],
    correctOptionId: 'opt_4_b',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    questionType: 'TRUE_FALSE',
    questionText: 'True or False: Sound travels faster in water than in air.',
    explanation: 'Because water is denser and less compressible than air, sound travels about 4.3 times faster through water (~1,480 m/s).',
    timeLimitSeconds: 15,
    points: 1000,
    sortOrder: 5,
    options: [
      { id: 'opt_5_t', text: 'True', sortOrder: 0 },
      { id: 'opt_5_f', text: 'False', sortOrder: 1 },
    ],
    correctOptionId: 'opt_5_t',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    questionType: 'MULTIPLE_CHOICE',
    questionText: 'What protocol translates human-readable domain names into IP addresses?',
    explanation: 'DNS (Domain Name System) functions as the phonebook of the Internet.',
    timeLimitSeconds: 20,
    points: 1000,
    sortOrder: 6,
    options: [
      { id: 'opt_6_a', text: 'DHCP', sortOrder: 0 },
      { id: 'opt_6_b', text: 'DNS', sortOrder: 1 },
      { id: 'opt_6_c', text: 'BGP', sortOrder: 2 },
      { id: 'opt_6_d', text: 'SMTP', sortOrder: 3 },
    ],
    correctOptionId: 'opt_6_b',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    questionType: 'MULTIPLE_CHOICE',
    questionText: 'Which celestial body in our solar system has the highest mountain and volcano (Olympus Mons)?',
    explanation: 'Olympus Mons on Mars rises over 21 kilometers (69,000 ft) above the surrounding Martian plains.',
    timeLimitSeconds: 20,
    points: 1000,
    sortOrder: 7,
    options: [
      { id: 'opt_7_a', text: 'Venus', sortOrder: 0 },
      { id: 'opt_7_b', text: 'Mars', sortOrder: 1 },
      { id: 'opt_7_c', text: 'Jupiter\'s moon Io', sortOrder: 2 },
      { id: 'opt_7_d', text: 'Mercury', sortOrder: 3 },
    ],
    correctOptionId: 'opt_7_b',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    questionType: 'MULTIPLE_CHOICE',
    questionText: 'In which year did the Apollo 11 mission successfully land the first humans on the Moon?',
    explanation: 'Neil Armstrong and Buzz Aldrin landed the Apollo Lunar Module Eagle on the Moon on July 20, 1969.',
    timeLimitSeconds: 20,
    points: 1000,
    sortOrder: 8,
    options: [
      { id: 'opt_8_a', text: '1965', sortOrder: 0 },
      { id: 'opt_8_b', text: '1969', sortOrder: 1 },
      { id: 'opt_8_c', text: '1971', sortOrder: 2 },
      { id: 'opt_8_d', text: '1973', sortOrder: 3 },
    ],
    correctOptionId: 'opt_8_b',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    questionType: 'MULTIPLE_CHOICE',
    questionText: 'What organelle produces the majority of chemical energy (ATP) in eukaryotic cells?',
    explanation: 'Mitochondria are known as the cellular powerhouses where oxidative phosphorylation takes place.',
    timeLimitSeconds: 20,
    points: 1000,
    sortOrder: 9,
    options: [
      { id: 'opt_9_a', text: 'Ribosome', sortOrder: 0 },
      { id: 'opt_9_b', text: 'Endoplasmic Reticulum', sortOrder: 1 },
      { id: 'opt_9_c', text: 'Mitochondria', sortOrder: 2 },
      { id: 'opt_9_d', text: 'Golgi Apparatus', sortOrder: 3 },
    ],
    correctOptionId: 'opt_9_c',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    questionType: 'TRUE_FALSE',
    questionText: 'True or False: The World Wide Web and the Internet are the exact same entity.',
    explanation: 'False: The Internet is the underlying global network of connected computers; the World Wide Web is a service/information system built on top of the Internet.',
    timeLimitSeconds: 15,
    points: 1000,
    sortOrder: 10,
    options: [
      { id: 'opt_10_t', text: 'True', sortOrder: 0 },
      { id: 'opt_10_f', text: 'False', sortOrder: 1 },
    ],
    correctOptionId: 'opt_10_f',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
